name: Test Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  DAY_OF_WEEK: "Monday"

jobs:
  VariableInYAML:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Step
        uses: actions/checkout@v6
      - name: Osman Definition in Job env
        run: |
          echo "Hello Osman"
          echo $OSMAN
        env:
          OSMAN: "set value to OSMAN"
      - name: Definition in public env
        run: |
          echo "Hello World 2"
          echo $DAY_OF_WEEK
  GlobalVariableInRepository:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  TestVariableAccessInMachine:
    runs-on: ubuntu-latest
    needs: VariableInYAML
    steps:
      - name: Checkout Step
        uses: actions/checkout@v6
      - shell: bash
        env:
          Super_User: "Makina içinden erişim için... Variable tanımlıyoruz. UserName: ${{ vars.DOCKERHUB_USERNAME }}"
        run: |
          echo "Hello Super User"
          echo $Super_User

  SaveOutput:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Step
        uses: actions/checkout@v6
      - name: Save Output to File
        run: |
          echo "Hello World 3" > output.log
          echo $DAY_OF_WEEK >> output.log
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-artifact
          path: output.log
  UploadArtifact:
    runs-on: ubuntu-latest
    needs: SaveOutput
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: output-artifact
      - name: Display Artifact Content
        run: |
          cat output.log

  Github_Output:
    runs-on: ubuntu-latest
    steps:
      - name: Set step output
        id: set_output
        run: echo "message=Hello from GITHUB_OUTPUT" >> "$GITHUB_OUTPUT"
      - name: Read step output
        run: echo "${{ steps.set_output.outputs.message }}"
    