name: Test Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Step
        uses: actions/checkout@v6
      - name: Enviroment variable list
        run: |
          echo "Environment Variables:"
          printenv
