name: Test Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  DAY_OF_WEEK: "Monday"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Step
        uses: actions/checkout@v6
      - name: Osman Definition in Job env
        run: |
          echo "Hello Osman"
          echo $OSMAN
        env:
          OSMAN: "set value to OSMAN"
      - name: Definition in public env
        run: |
          echo "Hello World 2"
          echo $DAY_OF_WEEK
  test2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Step
        uses: actions/checkout@v6
      - name: Osman Definition in Job env
        run: |
          echo "Hello Osman"
          echo $OSMAN
      - name: Definition in public env
        run: |
          echo "Hello World 2"
          echo $DAY_OF_WEEK

  test3:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Step
        uses: actions/checkout@v6
      - name: Osman Definition in Job env
        run: |
          echo "Hello Osman"
          echo $OSMAN
      - name: Definition in public env
        run: |
          echo "Hello World 2"
          echo $DAY_OF_WEEK